version: 0.0
os: linux 
hooks:
  AfterInstall:
    - location: untar_install.sh
      timeout: 5
    - location: install.sh
      timeout: 5
    - location: ../../../../../../root/start_or_reload_nginx_service.sh
      timeout: 5

